// Generated by CoffeeScript 1.10.0

/*
 * Example usage of lampyridae.coffee
 */

(function() {
  require('particle/bug');

  $(document).ready(function() {
    var animate, bugs, canvas, createBugs, numOfBugs, update;
    canvas = new Lampyridae.Canvas('world');
    Lampyridae.bugHueMax = 225;
    Lampyridae.bugHueMin = 180;
    Lampyridae.bugLightness = '65%';
    Lampyridae.bugOpacity = 0.15;
    Lampyridae.bugRadiusMax = 150;
    Lampyridae.bugRadiusMin = 15;
    Lampyridae.bugSpeedMax = 15;
    Lampyridae.bugSpeedMin = 5;
    Lampyridae.bugTurningAngle = 0.2 * Math.PI;
    numOfBugs = 50;
    bugs = [];
    createBugs = function() {
      var bug, i, j, ref;
      for (i = j = 0, ref = numOfBugs; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        bug = new Lampyridae.Bug(canvas);
        bugs.push(bug);
      }
    };
    animate = function() {
      canvas.draw.clear();
      update();
      requestAnimationFrame(animate);
    };
    update = function() {
      var i, j, ref;
      for (i = j = 0, ref = numOfBugs; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        bugs[i].update();
      }
    };
    createBugs();
    animate();
  });

}).call(this);
