// Generated by CoffeeScript 1.10.0

/*
 * Example usage of lampyridae.coffee
 */

(function() {
  var bubbles, canvas, createBubble, total, update;

  require('particle/firefly');

  canvas = new Lampyridae.Canvas('world');

  Lampyridae.Firefly.prototype.hueMax = 225;

  Lampyridae.Firefly.prototype.hueMin = 180;

  Lampyridae.Firefly.prototype.lightness = '65%';

  Lampyridae.Firefly.prototype.opacity = 0.15;

  Lampyridae.Firefly.prototype.radiusMax = 150;

  Lampyridae.Firefly.prototype.radiusMin = 15;

  Lampyridae.Firefly.prototype.speedMax = 15;

  Lampyridae.Firefly.prototype.speedMin = 5;

  Lampyridae.Firefly.prototype.turningAngle = 0.2 * Math.PI;

  total = 50;

  bubbles = [];

  createBubble = function() {
    var bubble, i, j, ref, results;
    results = [];
    for (i = j = 0, ref = total; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      bubble = new Lampyridae.Firefly(canvas);
      results.push(bubbles.push(bubble));
    }
    return results;
  };

  update = function() {
    var i, j, ref, results;
    results = [];
    for (i = j = 0, ref = total; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results.push(bubbles[i].update());
    }
    return results;
  };

  createBubble();

  canvas.addUpdate(canvas.draw.clear);

  canvas.addUpdate(update);

  canvas.animate();

}).call(this);
