// Generated by CoffeeScript 1.10.0

/* @file lampyridae.js
 * @Copyright (c) 2016 Taylor Siviter
 * This source code is licensed under the MIT License.
 * For full information, see the LICENSE file in the project root.
 */

(function() {
  var initL,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  initL = (function() {
    var err;
    if (window.Lampyridae == null) {
      return window.Lampyridae = {};
    } else {
      err = new Error('Lampyridae namespace could not be assigned. Is there a conflict?');
      err.name = 'FatalError';
      throw err;
    }
  })();


  /* Global application settings
   */

  window.Lampyridae.enableSimpleGlow = true;

  window.Lampyridae.timestep = 1;


  /* Common variables
   */

  window.Lampyridae.PI2 = 2.0 * Math.PI;


  /* 'Lightning' Bug specific variables
   */

  window.Lampyridae.bugHueMax = 102.72;

  window.Lampyridae.bugHueMin = 65.28;

  window.Lampyridae.bugSaturation = '100%';

  window.Lampyridae.bugLightness = '50%';

  window.Lampyridae.bugOpacity = 0.3;

  window.Lampyridae.bugRadiusMax = 50.5;

  window.Lampyridae.bugRadiusMin = 0.5;

  window.Lampyridae.bugSpeedMin = 1;

  window.Lampyridae.bugSpeedMax = 7;

  window.Lampyridae.bugTurningAngle = 0.1 * Math.PI;


  /* Available classes
   */

  window.Lampyridae.Bug;

  window.Lampyridae.Canvas;

  window.Lampyridae.Particle;


  /* Available functions
   */

  window.Lampyridae.hslToRgb;

  window.Lampyridae.rand;

  Lampyridae.Canvas = (function() {

    /* Construct and manage a canvas element
     *
     * @param id [String] Name of the #id selector for the canvas element
     * @param parent [String] Name of the element to attach the canvas to (defaults to body)
     * @todo Add options + add selection of an exisiting canvas
     */
    function Canvas(id, parent) {
      this.id = id;
      this.parent = parent != null ? parent : 'body';
      if (!(arguments.length > 0)) {
        throw new Error("Lampyridae: Canvas requires an \#id selector");
      }
      this.element = document.createElement('canvas');
      this.context = this.element.getContext('2d');
      this.setID();
      this.append();
      this.resizeToParent();
      $(window).resize((function(_this) {
        return function() {
          _this.resizeToParent();
        };
      })(this));
      return;
    }

    Canvas.prototype.width = function() {
      return $(this.element).width();
    };

    Canvas.prototype.height = function() {
      return $(this.element).height();
    };

    Canvas.prototype.setWidth = function(width) {
      if (width == null) {
        width = $(this.parent).innerWidth();
      }
      $(this.element).width(width).attr('width', width);
      return width;
    };

    Canvas.prototype.setHeight = function(height) {
      if (height == null) {
        height = $(this.parent).innerHeight();
      }
      $(this.element).height(height).attr('height', height);
      return height;
    };

    Canvas.prototype.setID = function(id) {
      this.id = id != null ? id : this.id;
      $(this.element).attr('id', this.id);
      return this.id;
    };

    Canvas.prototype.append = function(parent) {
      this.parent = parent != null ? parent : this.parent;
      $(this.parent).append(this.element);
      console.log("Lampyridae: Appended \#" + this.id + " to " + this.parent);
    };

    Canvas.prototype.resizeToParent = function() {
      this.setWidth();
      this.setHeight();
    };

    Canvas.prototype.clear = function() {
      this.context.clearRect(0, 0, this.width(), this.height());
    };

    return Canvas;

  })();


  /* Converts HSL colour to RGB.
   * Code adapted from:
   * @see https://github.com/bgrins/TinyColor
   * @see http://serennu.com/colour/rgbtohsl.php
   *
   * @param h [Number] The hue [0, 360]
   * @param s [Number] The saturation [0, 100]%
   * @param l [Number] The lightness [0, 100]%
   * @return [Array] The RGB representation [0, 255]
   */

  Lampyridae.hslToRgb = function(h, s, l) {
    var b, g, hue2rgb, p, q, r;
    h = parseFloat(h) / 360.0;
    s = parseFloat(s) / 100.0;
    l = parseFloat(l) / 100.0;
    if (s === 0) {
      r = g = b = l;
    } else {
      hue2rgb = function(p, q, t) {
        if (t < 0) {
          t += 1;
        }
        if (t > 1) {
          t -= 1;
        }
        if (t < 0.5) {
          return q;
        }
        if (t < 1 / 6) {
          return p + (q - p) * 6.0 * t;
        }
        if (t < 2 / 3) {
          return p + (q - p) * (4 - 6.0 * t);
        }
        return p;
      };
      q = l < 0.5 ? l * (1 + s) : l + s - (l * s);
      p = 2 * l - q;
      r = hue2rgb(p, q, h + 1 / 3);
      g = hue2rgb(p, q, h);
      b = hue2rgb(p, q, h - 1 / 3);
    }
    return [Math.round(255 * r), Math.round(255 * g), Math.round(255 * b)];
  };


  /*
   * Example usage
   */

  $(document).ready(function() {
    var animate, bugs, canvas, createBugs, numOfBugs, update;
    canvas = new Lampyridae.Canvas('world');
    numOfBugs = 50;
    bugs = [];
    createBugs = function() {
      var bug, i, j, ref;
      for (i = j = 0, ref = numOfBugs; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        bug = new Lampyridae.Bug(canvas);
        bugs.push(bug);
      }
    };
    animate = function() {
      canvas.clear();
      update();
    };
    update = function() {
      var i, j, ref;
      for (i = j = 0, ref = numOfBugs; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        bugs[i].update();
      }
    };
    createBugs();
    animate();
  });

  Lampyridae.Particle = (function() {

    /* Construct and manage a generic circular particle
     *
     * @param canvas [Object] Instance of Lampyridae.Canvas to attach the particle to
     * @param x [Number] Position of the particle along the x-axis
     * @param y [Number] Position of the particle along the y-axis
     * @param theta [Number] Direction of the particle (radians anticlockwise from the x-axis)
     * @param v [Number] Speed of the particle
     * @param r [Number] Radius of the particle
     * @param rgb [String] RGB Colour code of the particle - e.g. "rgb(255, 255, 255)"
     * @param a [Number] Opacity of the particle
     */
    function Particle(canvas1, x1, y1, theta, v1, radius, rgb, a1) {
      this.canvas = canvas1;
      this.x = x1;
      this.y = y1;
      this.theta = theta;
      this.v = v1;
      this.radius = radius;
      this.rgb = rgb;
      this.a = a1;
      return;
    }

    Particle.prototype.vx = function() {
      return this.v * Math.cos(this.theta);
    };

    Particle.prototype.vy = function() {
      return this.v * Math.sin(this.theta);
    };

    Particle.prototype.turn = function(angle) {
      if (angle == null) {
        angle = 0.0;
      }
      this.theta += angle;
    };

    Particle.prototype.turnAround = function() {
      this.turn(Math.PI);
    };

    Particle.prototype.move = function() {
      this.x += Lampyridae.timestep * this.vx();
      this.y += Lampyridae.timestep * this.vy();
    };

    Particle.prototype.isOutsideCanvas = function() {
      var ref, ref1;
      if (!((0.0 <= (ref = this.x) && ref <= this.canvas.width()))) {
        return true;
      } else if (!((0.0 <= (ref1 = this.y) && ref1 <= this.canvas.height()))) {
        return true;
      }
      return false;
    };

    Particle.prototype.applyHardBounds = function() {
      if (!this.isOutsideCanvas()) {
        this.randomTurn();
      } else {
        this.turnAround();
        while (!this.isOutsideCanvas()) {
          this.move;
        }
      }
      this.move();
    };

    Particle.prototype.update = function() {
      this.move();
      this.draw();
    };

    Particle.prototype.draw = function(r, a) {
      if (r == null) {
        r = this.radius;
      }
      if (a == null) {
        a = Lampyridae.PI2;
      }
      this.canvas.context.globalAlpha = 0.5;
      this.canvas.context.shadowBlur = 80;
      this.canvas.context.shadowColor = this.rgb;
      this.canvas.context.beginPath();
      this.drawCircle();
      this.canvas.context.closePath();
    };

    Particle.prototype.drawCircle = function(x, y, r, t, c) {
      if (x == null) {
        x = this.x;
      }
      if (y == null) {
        y = this.y;
      }
      if (r == null) {
        r = this.radius;
      }
      if (t == null) {
        t = Lampyridae.PI2;
      }
      if (c == null) {
        c = this.rgb;
      }
      this.canvas.context.arc(x, y, r, 0.0, t, false);
      this.canvas.context.fillStyle = c;
      return this.canvas.context.fill();
    };

    return Particle;

  })();

  Lampyridae.Bug = (function(superClass) {
    extend(Bug, superClass);


    /* Construct and manage a Lampyridae bug 'particle'
     *
     * @param canvas [Object] Instance of Lampyridae.Canvas to attach the bug to
     * @param x [Number] Position of the bug along the x-axis
     * @param y [Number] Position of the bug along the y-axis
     * @param t [Number] Direction of the bug (radians anticlockwise from the x-axis)
     * @param v [Number] Speed of the bug
     * @param r [Number] Radius of the bug
     * @param c [Array] RGB Colour code array of the bug - e.g. "[r, g, b]"
     */

    function Bug(canvas, x, y, t, v, r, c, a) {
      var h;
      if (!(arguments.length > 0)) {
        throw new Error("Lampyridae: Bug requires a valid Canvas instance to be attached to");
      }
      if (x == null) {
        x = Lampyridae.rand(0, canvas.width());
      }
      if (y == null) {
        y = Lampyridae.rand(0, canvas.height());
      }
      if (v == null) {
        v = Lampyridae.rand(Lampyridae.bugSpeedMin, Lampyridae.bugSpeedMax);
      }
      if (t == null) {
        t = Lampyridae.rand(0.0, Lampyridae.PI2);
      }
      if (r == null) {
        r = Lampyridae.rand(Lampyridae.bugRadiusMin, Lampyridae.bugRadiusMax);
      }
      h = Lampyridae.rand(Lampyridae.bugHueMin, Lampyridae.bugHueMax);
      if (c == null) {
        c = Lampyridae.hslToRgb(h, Lampyridae.bugSaturation, Lampyridae.bugLightness);
      }
      c = "rgb(" + c[0] + ", " + c[1] + ", " + c[2] + ")";
      if (a == null) {
        a = Lampyridae.bugOpacity;
      }
      Bug.__super__.constructor.call(this, canvas, x, y, t, v, r, c, a);
      return;
    }

    Bug.prototype.randomTurn = function() {
      this.turn(Lampyridae.bugTurningAngle * (2.0 * Math.random() - 1.0));
    };

    Bug.prototype.fly = function() {
      this.applyHardBounds();
    };

    Bug.prototype.update = function() {
      this.fly();
      this.draw();
    };

    return Bug;

  })(Lampyridae.Particle);


  /* Generates a random float from the given interval [l, u) where u > l
   *
   * @param l [Number] The lower bound of the interval
   * @param u [Number] The upper bound of the interval
   * @return [Number] Random number from the interval [l, u)
   */

  Lampyridae.rand = function(l, u) {
    if (arguments.length === 0) {
      return Math.random();
    }
    return (u - l) * Math.random() + l;
  };

}).call(this);
