// Generated by CoffeeScript 1.10.0

/*
 * Example usage of lampyridae.coffee
 */

(function() {
  require('particle/bug');

  $(document).ready(function() {
    var animate, bugs, canvas, createBugs, numOfBugs, update;
    canvas = new Lampyridae.Canvas('world');
    Lampyridae.bugHueMax = 70;
    Lampyridae.bugHueMin = 0;
    Lampyridae.bugLightness = '95%';
    Lampyridae.bugOpacity = 0.75;
    Lampyridae.bugRadiusMax = 0.5;
    Lampyridae.bugRadiusMin = 0.05;
    Lampyridae.bugSpeedMax = 0.4;
    Lampyridae.bugSpeedMin = 0.1;
    Lampyridae.bugTurningAngle = 4 * Math.PI;
    numOfBugs = 250;
    bugs = [];
    createBugs = function() {
      var bug, i, j, ref;
      for (i = j = 0, ref = numOfBugs; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        bug = new Lampyridae.Bug(canvas);
        bugs.push(bug);
      }
    };
    animate = function() {
      canvas.draw.clear();
      update();
      requestAnimationFrame(animate);
    };
    update = function() {
      var i, j, ref;
      for (i = j = 0, ref = numOfBugs; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        bugs[i].update();
      }
    };
    createBugs();
    animate();
  });

}).call(this);
